// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCOMQOopOdNA8STxkny4TJpLpSE58-e2E',
    appId: '1:103340480130:web:ea6424cc19745a6480069b',
    messagingSenderId: '103340480130',
    projectId: 'smartfarm-4b650',
    authDomain: 'smartfarm-4b650.firebaseapp.com',
    storageBucket: 'smartfarm-4b650.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk9B4FVSqhAbvL0b5KtrWKcWQfGItcfr0',
    appId: '1:103340480130:android:33a8daf274e2df5280069b',
    messagingSenderId: '103340480130',
    projectId: 'smartfarm-4b650',
    storageBucket: 'smartfarm-4b650.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-du7wLLHfH2coDV1aBNBmb-tLlvHP89U',
    appId: '1:103340480130:ios:e2c13a2fa170dbca80069b',
    messagingSenderId: '103340480130',
    projectId: 'smartfarm-4b650',
    storageBucket: 'smartfarm-4b650.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-du7wLLHfH2coDV1aBNBmb-tLlvHP89U',
    appId: '1:103340480130:ios:a6050c1b3692e1e180069b',
    messagingSenderId: '103340480130',
    projectId: 'smartfarm-4b650',
    storageBucket: 'smartfarm-4b650.appspot.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
